### ISSUE TITLE
断点下载安装

### ISSUE THREAD

**Issue by xhg221** [xuexiangjys/XUpdateAPI#1]
采用断点下载时，遇到以下问题

Apk更新下载完成后，跳转到安装界面，这时不安装，点击取消按钮；取消后返回到APP，再次点击升级，升级框瞬间消失，进度显示100%，无法弹出Apk安装界面；

测试机：vivo  android10

**Comment by xhg221** [comment]
采用断点下载时，遇到以下问题

Apk更新下载完成后，跳转到安装界面，这时不安装，点击取消按钮；取消后返回到APP，再次点击升级，升级框瞬间消失，进度显示100%，无法弹出Apk安装界面；

刚试了其他测试机，也是同样的问题存在

**Comment by xuexiangjys** [comment]
首先呢,你问题的时候,最好提供一下错误日志,这样节省大家时间,方便我定位问题.
其次,看你的描述,我猜测你是没有设置md5值导致.因为设置md5的话,下次是需要重新下载的.所以如果需要使用断点下载安装的话,请设置md5值,否则就没有任何意义了.
