### ISSUE TITLE
请问使用XUpdateApi时，是否可以自定义自定义弹窗layout

### ISSUE THREAD

**Issue by el0310-axin** [xuexiangjys/XUpdateAPI#13]
直接使用的XUpdateApi，请问是否支持自定义弹窗dialog的layout，或者修改xupdate_dialog_update.xml呢？因为现有的样式不太能满足需求

**Comment by xuexiangjys** [comment]
支持自定义弹窗layout,可以直接修改xupdate_dialog_update.xml(前提是view的id不能丢失,并且view的类型不能随意修改) 或者 自定义IUpdatePrompter,都是可以的
