### ISSUE TITLE
使用EasyUpdate.checkUpdate 没有任何响应

### ISSUE THREAD

**Issue by nikolamakin** [xuexiangjys/XUpdateAPI#2]
你好：
class MainActivity : AppCompatActivity() {

    private lateinit var bind: ActivityMainBinding

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        /**
         * 版本更新
         */
        EasyUpdate.checkUpdate(this,Http.httpVersion)
   }
}

build app 没有任何反应，日志也没有报错和警告,
版本1.0
服务器输出的json 是 1.0.1
md5 都有
请问可能的原因会是哪方面，谢谢

**Comment by nikolamakin** [comment]
ApkMd5: "539d45449a2e29b0bd3dbf44ccd7b0df"
ApkSize: 7845196
Code: 0
DownloadUrl: "http://1.0.14.18/appVersion/app-1.0.1.apk"
ModifyContent: "1、优化api接口。\r\n2、添加使用demo演示。\r\n3、新增自定义更新服务API接口。\r\n4、优化更新提示界面。"
Msg: ""
UpdateStatus: 1
VersionCode: 1
VersionName: "1.0.1"

**Comment by nikolamakin** [comment]
> 你好：
> class MainActivity : AppCompatActivity() {
> 
> ```
> private lateinit var bind: ActivityMainBinding
> 
> override fun onCreate(savedInstanceState: Bundle?) {
>     super.onCreate(savedInstanceState)
>     /**
>      * 版本更新
>      */
>     EasyUpdate.checkUpdate(this,Http.httpVersion)
> ```
> 
> }
> }
> 
> build app 没有任何反应，日志也没有报错和警告,
> 版本1.0
> 服务器输出的json 是 1.0.1
> md5 都有
> 请问可能的原因会是哪方面，谢谢

**Comment by ram16g** [comment]
@nikolamakin 最后怎么解决的呢？
