### ISSUE TITLE
不能下载okhttputils

### ISSUE THREAD

**Issue by yuexunshi** [xuexiangjys/XUpdateAPI#7]
> Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
   > Could not find com.zhy:okhttputils:2.6.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/zhy/okhttputils/2.6.2/okhttputils-2.6.2.pom
       - https://repo.maven.apache.org/maven2/com/zhy/okhttputils/2.6.2/okhttputils-2.6.2.pom
       - https://frontjs-static.pgyer.com/dist/sdk/pgyersdk/com/zhy/okhttputils/2.6.2/okhttputils-2.6.2.pom
       - https://jitpack.io/com/zhy/okhttputils/2.6.2/okhttputils-2.6.2.pom
     Required by:
         project :app > com.github.xuexiangjys.XUpdateAPI:xupdate-easy:1.0.1

**Comment by xuexiangjys** [comment]
maven { url 'https://maven.aliyun.com/repository/public' }
用阿里的镜像仓库
