### ISSUE TITLE
下载100%但是没有自动安装

### ISSUE THREAD

**Issue by rushuni2023** [xuexiangjys/XUpdateAPI#9]
请问 下载100%后，窗口消失了，没有弹出安装界面，是什么原因呢？

**Comment by rushuni2023** [comment]
<img width="895" alt="image" src="https://user-images.githubusercontent.com/120305471/226074752-243e45d5-ed74-4cb3-abda-35d51387e5a9.png">

使用的Android 11，断点下载，静默安装，XUpdateAPI，XUpdate的更新方法都是试过了，都是进度条100%后就没了，没有弹出安装

**Comment by xisohi** [comment]
您好，我也出现了这个问题，您是怎么解决的
